#!perl -w

use strict;

use CPAN::Config;

eval "use CPAN::FindDependencies;";
if($@) {
    print STDERR "Couldn't load CPAN::FindDependencies.\n";
    print STDERR "Check permissions on $CPAN::Config{cpan_home}\n";
}

my @deps = CPAN::FindDependencies::finddeps(shift, nowarnings => 1);
foreach my $dep (@deps) {
    print '  ' x $dep->depth();
    print $dep->name().
          ' ('.$dep->distribution().")\n";
}
           
